### PR TITLE
types: add workaround for uploadReleaseAsset

### LINKED ISSUE #73: Incorrect type for "repos.uploadReleaseAsset"
**What happened?**

In octokit v16 `repos.uploadReleaseAsset` accepted `string | object` for the `data` prop.

In octokit v17 it only accepts a `string`. Running the code with `as any` though providing a buffer is still valid.

https://github.com/intuit/auto/blob/master/plugins/upload-assets/src/index.ts#L70

**What did you expect to happen?**

This endpoint should still accept a `Buffer`.

**What the problem might be**

I tried finding the place to contribute it but was unable since it is generated from somewhere else

### PR DESCRIPTION
**Pull request by copperwall**
This adds a workaround in typescript.js to override the data parameter
type for ReposUploadReleaseAssetEndpoint. The endpoint type from the
openapi graphql server only specifies  string as a type, when it can
take a string or a Buffer.

Closes #73

### CODE REVIEW

File: scripts/update-endpoints/typescript.js [hunk 1]
```diff
@@ -149,6 +149,9 @@ async function run() {
           "For https://api.github.com, set `baseUrl` to `https://uploads.github.com`. For GitHub Enterprise Server, set it to `<your hostname>/api/uploads`",
         required: true,
       });
+
+      const data = parameters.find((parameter) => parameter.name === "data");
+      data.type = "string | Buffer";
```
Comment (gr2m) [inline scripts/update-endpoints/typescript.js:154]: That's great, thank you!

Can you also update the comment in line 143? The comment could just say

```js
// workarounds for "Upload a release asset"
```

and then add separate comments above the two respective workarounds explaining what is happening

Comment (copperwall) [reply scripts/update-endpoints/typescript.js:154]: Most definitely, I'll add those in.

**Comment by copperwall** [comment]
Thanks @gr2m, I appreciate it!
